config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'homes/top'
    patch 'user/unsubscribe' => "users#unsubscribe"
    resources :posts, only: [:show, :edit, :update]
    resources :users, only: [:show, :update]
  end
  namespace :public do
    
    get 'users/home' => "users#home"
    get "searches", to: "searches#searches_result"
    get 'posts/get_city', to: 'posts#get_city'
    get 'homes/about'
    get 'users/confirm'
    patch 'users/unsubscribe'
    resources :posts do  #postsコントローラへのルーティング  
      resources :comments, only: [:create, :destroy]  #commentsコントローラへのルーティング
    end
    resources :posts, only: [:show, :new, :create, :update]
    resources :posts do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, ]
    resources :users do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end
    resources :users do
      member do
        get :favorites
      end
    end
  end
  


  
  root to: "public/homes#top"
  
  devise_for :users,controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    if admin_signed_in?
      @posts = Post.all.order(created_at: :desc)
      @users = User.all.order(created_at: :desc)
    end
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row m-3">
    <% if admin_signed_in? %>
    <div class="col coi-6">
      <h3>投稿一覧</h3>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>公開</th>
            <th>ユーザー名</th>
            <th>タイトル</th>
            <th>写真</th>
            <th>投稿日時</th>
            <th>いいね数</th>
          </tr>
        </thead>
        <% @posts.each do |post| %>
            <tbody>
              <tr>
                <td><%= post.is_active %></td>
                <td><%= link_to admin_user_path(post.user.id) do %><%= post.user.user_nickname %><% end %></td>
                <td><%= link_to admin_post_path(post.id) do %> <%= post.title %><% end %></td>
                <td><% if post.image.attached? %><%= image_tag post.image, size: "50x50" %><% else %><%= image_tag 'no_image', size: "50x50" %><% end %></td>
                <td><%= post.created_at.to_s(:datetime_jp) %></td>
                <td><%= post.favorites.count %>いいね</td>
              </tr>
            </tbody>
        <% end %>
      </table>
    </div>
    <div class="col coi-6">
      <h3>ユーザー一覧</h3>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>退会</th>
            <th>プロフィール画像</th>
            <th>ユーザー名</th>
            <th>フォロー数</th>
            <th>フォロワー数</th>
            <th>投稿数</th>
            <th>登録日時</th>
          </tr>
        </thead>
        <% @users.each do |user| %>
            <tbody>
              <tr>
                <td><%= user.is_active %></td>
                <td><%= image_tag user.get_profile_image(50,50) %></td>
                <td><%= link_to admin_user_path(user.id) do %><%= user.user_nickname %><% end %></td>
                <td><%= user.followings.count %></td>
                <td><%= user.followers.count %></td>
                <td><%= user.posts.count %></td>
                <td><%= user.created_at.to_s(:datetime_jp) %></td>
              </tr>
            </tbody>
        <% end %>
      </table>
    </div>
    <% end %>
  </div>
 </div>