config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'homes/top'
    patch 'user/unsubscribe' => "users#unsubscribe"
    resources :posts, only: [:show, :edit, :update]
    resources :users, only: [:show, :update]
  end
  namespace :public do
    
    get 'users/home' => "users#home"
    get "searches", to: "searches#searches_result"
    get 'posts/get_city', to: 'posts#get_city'
    get 'homes/about'
    get 'users/confirm'
    patch 'users/unsubscribe'
    resources :posts do  #postsコントローラへのルーティング  
      resources :comments, only: [:create, :destroy]  #commentsコントローラへのルーティング
    end
    resources :posts, only: [:show, :new, :create, :update]
    resources :posts do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, ]
    resources :users do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end
    resources :users do
      member do
        get :favorites
      end
    end
  end
  


  
  root to: "public/homes#top"
  
  devise_for :users,controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true, length: {maximum:10}
  validates :last_name, presence: true, length: {maximum:10}
  validates :telephone_number, presence: true, length: {maximum:15}
  validates :user_nickname, presence: true, length: {maximum:20}

  # フォローした、されたの関係
  has_many :follows, class_name: "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy
  # 一覧画面で使う
  has_many :followings, through: :follows, source: :followed
  has_many :followers, through: :reverse_of_follows, source: :follower
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments
  has_one_attached :profile_image

  scope :active_data, -> { where(is_active: false) }

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("user_nickname LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("user_nickname LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  # フォローしたときの処理
  def follow(user_id)
    follows.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    follows.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = Post.where(user_id: params[:id])
  end

  def unsubscribe
    @user = User.find(params[:id])
    @user.update(is_active: true)
    flash[:notice] = "退会しました。"
    redirect_to admin_homes_top_path
  end


  private
  def user_params
    params.require(:user).permit(:is_active)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-3">
      <%= image_tag @user.get_profile_image(100,100) %>
    </div>
    <div class="col col-5">
      <table>
        <tr>
          <th><label><%= @user.user_nickname %></label></th>
          <td>さん</td>
        </tr>
        <tr>
          <td>フォロー<%= @user.followings.count %></td>
          <td>フォロワー<%= @user.followers.count %></td>
        </tr>
      </table>
      <p><% if @user.is_active == false %><%= link_to "このユーザーを退会させる", admin_user_unsubscribe_path(id: @user.id), method: :patch %><% end %></p>
    </div>
    <div class="col col-4">
      <%= @user.self_introduction %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <table class='table table-hover table-inverse'>
        <h5><strong>投稿した思い出</strong></h5>
        <thead>
          <tr>
            <th>公開ステータス</th>
            <th>ユーザー</th>
            <th>投稿タイトル</th>
            <th>写真</th>
            <th>いいね数</th>
            <th>投稿日時</th>
          </tr>
        </thead>
        <% @posts.each do |post| %>
          <tbody>
            <tr>
              <td><%= post.is_active %></td>
              <td><%= post.user.user_nickname %></td>
              <td><%= link_to admin_post_path(post.id) do %> <%= post.title %><% end %></td>
              <td><% if post.image.attached? %><%= image_tag post.image, size: "50x50" %><% else %><%= image_tag 'no_image', size: "50x50" %><% end %></td>
              <td><%= post.favorites.count %></td>
              <td><%= post.created_at.to_s(:datetime_jp) %></td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>