config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'homes/top'
    patch 'user/unsubscribe' => "users#unsubscribe"
    resources :posts, only: [:show, :edit, :update]
    resources :users, only: [:show, :update]
  end
  namespace :public do
    
    get 'users/home' => "users#home"
    get "searches", to: "searches#searches_result"
    get 'posts/get_city', to: 'posts#get_city'
    get 'homes/about'
    get 'users/confirm'
    patch 'users/unsubscribe'
    resources :posts do  #postsコントローラへのルーティング  
      resources :comments, only: [:create, :destroy]  #commentsコントローラへのルーティング
    end
    resources :posts, only: [:show, :new, :create, :update]
    resources :posts do
      resource :favorites, only: [:create, :destroy]
    end
    resources :users, only: [:show, :edit, :update, ]
    resources :users do
      resource :follows, only: [:create, :destroy]
      get 'followings' => 'follows#followings', as: 'followings'
      get 'followers' => 'follows#followers', as: 'followers'
    end
    resources :users do
      member do
        get :favorites
      end
    end
  end
  


  
  root to: "public/homes#top"
  
  devise_for :users,controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>COOLJourney</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header id="header" class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="rogo navbar-brand p-3" href="/public/homes/about"><h1>Cool Journey</h1></a>
          <button class="btn btn-primary navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div><%= render 'public/searches/search' %></div>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-gradient" %>
                </li>
                <li class="nav-item">
                  <%= link_to "ホーム", admin_homes_top_path, class: "btn btn-gradient" %>
                </li>
                <% elsif user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-gradient" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to"マイページ", public_user_path(current_user.id), class: "btn btn-gradient" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to"新規投稿", new_public_post_path, class: "btn btn-gradient" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to"タイムライン", public_users_home_path, class: "btn btn-gradient" %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to"タイムライン", public_users_home_path, class: "btn btn-gradient" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "新規登録", new_user_registration_path, class: "btn btn-gradient" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_user_session_path, class: "btn btn-gradient" %>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main id="main">
    <%= yield %>
    </main>
  </body>
</html>